import { ColorModeScript } from '@chakra-ui/react';
import type { Metadata } from 'next';
import { Html, Head, NextScript } from 'next/document';
import { Providers, theme } from './providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: React.ReactNode;
};

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <Html lang="en">
      <Head />
      <body>
        <ColorModeScript initialColorMode={theme.config.initialColorMode} />
        <Providers>{children}</Providers>
        <NextScript />
      </body>
    </Html>
  );
};

export default RootLayout;
